site_name: TaPS
site_url: https://taps.proxystore.dev/
site_author: Globus Labs
site_description: Task Performance Suite

repo_name: proxystore/taps
repo_url: https://github.com/proxystore/taps

copyright: Copyright &copy; 2024-Present Globus Labs

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    text: Open Sans
    code: Roboto Mono
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: globus-blue
      accent: globus-blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: globus-light
      accent: globus-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: globus-dark
      accent: globus-dark
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  overrides: docs/_overrides
  # favicon: static/favicon.png
  # icon:
  #   logo: logo

watch:
  - mkdocs.yml
  - README.md
  - docs/
  - taps/

extra:
  version:
    default: latest
    provider: mike

extra_css:
  - css/extra.css
  - css/mkdocstrings.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: proxystore
      repo: taps
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home:
      - Overview: index.md
      - Get Started: get-started.md
      - Issues (GitHub): https://github.com/proxystore/taps/issues
      - Changelog (GitHub): https://github.com/proxystore/taps/releases
  - Apps:
      - apps/index.md
      - Cholesky Factorization: apps/cholesky.md
      - Docking Proteins: apps/docking.md
      - Federated Learning: apps/fedlearn.md
      - MapReduce: apps/mapreduce.md
      - Molecular Design: apps/moldesign.md
      - Montage: apps/montage.md
      - Synthetic: apps/synthetic.md
  - Guides:
      - guides/index.md
      - Create an Application: guides/creating-apps.md
  - API Reference:
      - TaPS: api/
  - Contributing:
      - contributing/index.md
      - Style Guide: contributing/style-guide.md
      - Issues and Pull Requests: contributing/issues-pull-requests.md
      - Releases: contributing/releases.md

plugins:
  - mike:
      alias_type: symlink
      canonical_version: latest
  - gen-files:
      scripts:
        - docs/generate_api.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      custom_templates: docs/_templates
      enable_inventory: true
      handlers:
        python:
          setup_commands:
            - import pytkdocs_tweaks
            - pytkdocs_tweaks.main()
          import:
            - https://docs.python.org/3/objects.inv
            - https://docs.proxystore.dev/main/objects.inv
            - https://extensions.proxystore.dev/main/objects.inv
            - https://distributed.dask.org/en/latest/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv
            - https://numpy.org/doc/stable/objects.inv
          options:
            annotations_path: brief
            docstring_section_style: list
            docstring_style: google
            inherited_members: yes
            line_length: 60
            members_order: source
            merge_init_into_class: yes
            separate_signature: yes
            show_root_members_full_path: no
            show_object_full_path: no
            show_root_full_path: yes
            show_signature_annotations: yes
            show_submodules: no
            signature_crossrefs: yes
  - search
  - section-index
